# Generated by Django 4.1.3 on 2022-11-05 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0002_habit_dailyrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='amount_completed',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='dailyrecord',
            constraint=models.UniqueConstraint(fields=('habit', 'date', 'user'), name='unique_constraint'),
        ),
    ]
